package me.alex4386.typhon.server;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HexFormat;
import me.alex4386.typhon.server.protocol.Codecs;
import org.junit.jupiter.api.Test;

/**
 * Cross-implementation check of the binary codecs. This test writes
 * {@code visualizer/src/protocol/golden-java.json} (frames encoded by the Java server); the
 * visualizer's vitest suite ({@code golden.test.ts}) decodes them with the TypeScript decoder and
 * re-encodes the same values with the TypeScript encoder, which must produce byte-identical
 * uncompressed payloads. Run with {@code -Dtyphon.golden.write=true} to refresh the file.
 */
class GoldenFramesTest {
    static final Path FILE = Path.of("..", "visualizer", "src", "protocol", "golden-java.json");

    static float[] ramp(int n, float base, float step) {
        float[] v = new float[n];
        for (int i = 0; i < n; i++) v[i] = base + step * ((i * 37) % n);
        return v;
    }

    static JsonObject build() {
        JsonArray tiles = new JsonArray();
        int w = 16;
        int h = 16;
        int n = w * h;
        Object[][] cases = {
                {1, Codecs.ELEVATION_U16_CM_DELTA, ramp(n, 512.25f, 0.731f), 0.0, 0.0},
                {2, Codecs.DEPTH_U16_MM_SPARSE, sparse(n), 0.0, 0.0},
                {2, Codecs.DEPTH_U16_MM_DENSE, ramp(n, 0, 0.0137f), 0.0, 0.0},
                {3, Codecs.TEMPERATURE_U8_LOG, ramp(n, 0, 5.0f), 1300.0, 0.0},
                {10, Codecs.U16_RAW, units(n), 0.0, 0.0},
                {4, Codecs.F32_RAW, ramp(n, -3.5f, 0.125f), 0.0, 0.0},
                {12, Codecs.U8_LINEAR, ramp(n, 0, 1f / n), 0.0, 1.0},
        };
        for (Object[] c : cases) {
            int field = (int) c[0];
            int codec = (int) c[1];
            float[] values = (float[]) c[2];
            double a = (double) c[3];
            double b = (double) c[4];
            Codecs.Payload p = Codecs.encode(values, codec, a, b);
            byte[] frame = Codecs.tileFrame(field, p, 3, -2, 42, w, h, 1234.5);
            JsonObject o = new JsonObject();
            o.addProperty("field", field);
            o.addProperty("codec", codec);
            o.addProperty("width", w);
            o.addProperty("height", h);
            JsonArray vals = new JsonArray();
            for (float v : values) vals.add(v);
            o.add("values", vals);
            o.addProperty("a", a);
            o.addProperty("b", b);
            o.addProperty("payloadHex", HexFormat.of().formatHex(p.bytes()));
            o.addProperty("frameHex", HexFormat.of().formatHex(frame));
            tiles.add(o);
        }

        int nu = 8;
        int nz = 4;
        int px = nu * nz;
        float[] surface = ramp(nu, 100.5f, 2f);
        float[] water = new float[nu];
        for (int i = 0; i < nu; i++) water[i] = i % 2 == 0 ? Float.NaN : 90 + i;
        byte[] material = new byte[px];
        int[] unit = new int[px];
        float[] temp = new float[px];
        float[] sat = new float[px];
        float[] steam = new float[px];
        byte[] flags = new byte[px];
        for (int p = 0; p < px; p++) {
            material[p] = (byte) (p % 7);
            unit[p] = p % 5 == 0 ? 0 : 1000 + p;
            temp[p] = 20 * p;
            sat[p] = p / (float) px;
            steam[p] = 1 - p / (float) px;
            flags[p] = (byte) (p % 16);
        }
        String meta = "{\"requestId\":9,\"length\":800,\"zMin\":-100,\"zMax\":300,\"units\":[],\"overlays\":[]}";
        byte[] section = Codecs.sectionFrame(9, nu, nz, 77.25,
                new Codecs.SectionBody(meta, surface, water, material, unit, temp, sat, steam, flags));
        JsonObject sec = new JsonObject();
        sec.addProperty("frameHex", HexFormat.of().formatHex(section));
        sec.addProperty("nu", nu);
        sec.addProperty("nz", nz);
        sec.addProperty("meta", meta);
        JsonArray units = new JsonArray();
        for (int u : unit) units.add(u);
        sec.add("unit", units);
        JsonArray surf = new JsonArray();
        for (float v : surface) surf.add(v);
        sec.add("surfaceZ", surf);

        JsonObject root = new JsonObject();
        root.addProperty("comment", "Generated by sim-server GoldenFramesTest; decoded by golden.test.ts.");
        root.add("tiles", tiles);
        root.add("section", sec);
        return root;
    }

    static float[] sparse(int n) {
        float[] v = new float[n];
        for (int i = 0; i < n; i += 7) v[i] = 0.001f * (i + 1) * 13;
        return v;
    }

    static float[] units(int n) {
        float[] v = new float[n];
        for (int i = 0; i < n; i++) v[i] = (i * 211) % 65536;
        return v;
    }

    @Test
    void goldenFileMatchesCurrentEncoder() throws Exception {
        String json = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().serializeSpecialFloatingPointValues()
                .create().toJson(build()) + "\n";
        if (Boolean.getBoolean("typhon.golden.write") || !Files.exists(FILE)) {
            Files.writeString(FILE, json, StandardCharsets.UTF_8);
        }
        assertEquals(json, Files.readString(FILE), "golden-java.json is stale: rerun with -Dtyphon.golden.write=true");
    }

    @Test
    void javaDecoderRoundTripsEveryCodec() {
        JsonObject root = build();
        for (var e : root.getAsJsonArray("tiles")) {
            JsonObject o = e.getAsJsonObject();
            Codecs.TileFrame f = Codecs.decodeTileFrame(HexFormat.of().parseHex(o.get("frameHex").getAsString()));
            JsonArray vals = o.getAsJsonArray("values");
            assertEquals(vals.size(), f.values().length);
            for (int i = 0; i < vals.size(); i++) {
                float v = vals.get(i).getAsFloat();
                float tol = switch (f.codec()) {
                    case Codecs.ELEVATION_U16_CM_DELTA -> 0.006f;
                    case Codecs.DEPTH_U16_MM_SPARSE, Codecs.DEPTH_U16_MM_DENSE -> 0.0006f;
                    case Codecs.TEMPERATURE_U8_LOG -> Math.max(0.5f, v * 0.03f);
                    case Codecs.U8_LINEAR -> 0.002f;
                    default -> 0;
                };
                assertEquals(v, f.values()[i], tol, "codec " + f.codec() + " index " + i);
            }
            assertEquals(42, f.version());
            assertEquals(-2, f.tileY());
        }
        Codecs.SectionFrame s = Codecs.decodeSectionFrame(
                HexFormat.of().parseHex(root.getAsJsonObject("section").get("frameHex").getAsString()));
        assertEquals(9, s.requestId());
        assertEquals(8, s.nu());
        int[] expected = new int[32];
        JsonArray u = root.getAsJsonObject("section").getAsJsonArray("unit");
        for (int i = 0; i < 32; i++) expected[i] = u.get(i).getAsInt();
        assertArrayEquals(expected, s.unit());
    }
}
