# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy to Test Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: setting up deploy environment
      run: |
        cd .deploy
        npm i -g yarn
        yarn
    - name: setting up minehub credentials
      run: |
        echo -n "${MINEHUB_SECRETS}" > .deploy/.secrets.json
      env:
        MINEHUB_SECRETS: ${{ secrets.MINEHUB_SECRETS }}
    - name: Run Deploy
      run: |
        ./deploy.sh
