# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.16
      uses: actions/setup-java@v1
      with:
        java-version: 1.16
    - name: Setup Spigot Build Environment
      run: |
        mkdir BuildTools
        cd BuildTools
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        java -jar BuildTools.jar --rev latest
        cd ..
    - name: Build with Maven
      run: mvn
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Typhon.jar
        # A file, directory or wildcard pattern that describes what to upload
        path: target/**/typhon-*.jar
      
