name: Build Release Jar

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1200

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Update version of maven file to ${{ github.event.release.tag_name }}
        run: mvn versions:set -DnewVersion=${VER_TAG:1}
        env:
          VER_TAG: ${{ github.event.release.tag_name }}
      - name: Build with Maven
        run: mvn package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: Typhon.jar
          # A file, directory or wildcard pattern that describes what to upload
          path: target/**/typhon-*.jar
      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/**/typhon-*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
